name: myapp
description: "For survey road monitoring."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  wifi_iot: ^0.3.19+1
  video_player: ^2.9.2
  flutter_countdown_timer: ^4.1.0
  flutter_blue_plus: ^1.0.2
  logger: ^2.5.0
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  get: ^4.6.5
  network_info_plus: ^6.1.1
  location: ^7.0.1
  pull_to_refresh: ^2.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
  - assets/images/logoLogin.jpeg
  - assets/images/profile_image.jpg
  - assets/images/gopro.png